name = "VIDA"
uuid = "4096cdfb-f084-40a3-b02d-1a2a54920cb8"
authors = ["Paul <ptiede91@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
